# Generated by Django 5.2.7 on 2025-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('butcher', 'Butcher'), ('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('grocery', 'Grocery'), ('propane', 'Propane')], db_index=True, default='butcher', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
