# Generated by Django 5.2.7 on 2025-11-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_department_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meat_type',
            field=models.CharField(blank=True, choices=[('beef', 'Beef'), ('pork', 'Pork'), ('chicken', 'Chicken'), ('turkey', 'Turkey'), ('lamb', 'Lamb'), ('fish', 'Fish'), ('seafood', 'Seafood'), ('other', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('ea', 'Each'), ('lb', 'Pound (lb)'), ('kg', 'Kilogram (kg)')], max_length=2),
        ),
    ]
