# Generated by Django 5.2.7 on 2025-11-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
