# Generated by Django 5.2.7 on 2025-11-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_quantity'),
    ]

    operations = [
    ]
