# Generated by Django 5.2.7 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_map_old_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('created', 'Created'), ('pending', 'Pending Payment'), ('accepted', 'Accepted'), ('dispatched', 'Dispatched'), ('preparing', 'Preparing'), ('ready', 'Ready for Pickup'), ('complete', 'Complete'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
    ]
