# Generated by Django 5.2.7 on 2025-11-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
    ]
