# Generated by Django 5.2.7 on 2025-11-11 22:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_map_old_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
